"""add_source_url_and_saved_at_to_article

Revision ID: 00bea7ada5a4
Revises: b9cc0b6d928d
Create Date: 2026-07-31 12:11:38.032975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00bea7ada5a4'
down_revision: Union[str, Sequence[str], None] = 'b9cc0b6d928d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('source_url', sa.String(), nullable=False))
    op.add_column('article', sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'saved_at')
    op.drop_column('article', 'source_url')
    # ### end Alembic commands ###
