"""rename_username_to_display_name

Revision ID: b4fa62a12b5b
Revises: 34ebfd33ecfe
Create Date: 2026-08-04 16:29:01.974983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fa62a12b5b'
down_revision: Union[str, Sequence[str], None] = '34ebfd33ecfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.alter_column('user', 'username', new_column_name='display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'display_name', new_column_name='username')
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    # ### end Alembic commands ###
